version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdpremote
      POSTGRES_SERVER: postgres
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    command: server --console-address ":9001" /data

  sdpremote:
    build: .
    ports:
      - 8000:8000
    depends_on:
    - postgres
    - minio
    environment:
      SDP_REMOTE_DATABASE__uri: 'postgresql+asyncpg://postgres:postgres@postgres:5432/sdpremote'
      SDP_REMOTE_DATABASE__uri_sync: 'postgresql+pg8000://postgres:postgres@postgres:5432/sdpremote'
      SDP_REMOTE_STORAGE__endpoint: 'minio:9000'
      SDP_REMOTE_STORAGE__access_key: 'minio'
      SDP_REMOTE_STORAGE__secret_key: 'miniopass'

volumes:
  postgres_data:
  minio_data:
