version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sdpremote
      POSTGRES_SERVER: postgres
    ports:
      - 5432:5432

volumes:
  postgres_data:
