"""add objects table

Revision ID: 4cbaef1dee3d
Revises: 6d36be018ad1
Create Date: 2021-07-26 17:30:11.771022

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4cbaef1dee3d'
down_revision = '6d36be018ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # type: ignore
        'objects',
        sa.Column('key', sa.Text(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('repo', sa.Text(), nullable=False),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('creator', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('data', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['data'],
            ['storage.id'],
            name=op.f('fk__objects__data__storage'),  # type: ignore
            onupdate='CASCADE',
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['name', 'repo'],
            ['scopes.name', 'scopes.repo'],
            name=op.f('fk__objects__name_repo__scopes'),  # type: ignore
            onupdate='CASCADE',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'key',
            'name',
            'repo',
            name=op.f('pk__objects'),  # type: ignore
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')  # type: ignore
    # ### end Alembic commands ###
