"""add repos table

Revision ID: 52811586999c
Revises: 
Create Date: 2021-07-25 12:10:13.388266

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '52811586999c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # type: ignore
        'repos',
        sa.Column('name', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint(
            'name',
            name=op.f('pk__repos'),  # type: ignore
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repos')  # type: ignore
    # ### end Alembic commands ###
