"""add owner to storage table

Revision ID: 6e301d833b85
Revises: 4cbaef1dee3d
Create Date: 2021-07-26 19:21:24.363593

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6e301d833b85'
down_revision = '4cbaef1dee3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(  # type: ignore
        'storage',
        sa.Column('owner', sa.Text(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage', 'owner')  # type: ignore
    # ### end Alembic commands ###
